CREATE TABLE SENSO
(
ANO INT NOT NULL,
COD_UF CHAR(2) NOT NULL,
ESTADO VARCHAR2(50) NOT NULL,
COD_MUN CHAR(7) NOT NULL,
NOME_MUN VARCHAR(50) NOT NULL,
REGIAO VARCHAR(150),
COD_MESO_REG CHAR(4),
NOME_MESO_REG VARCHAR(100) NOT NULL,
COD_MIC_REG CHAR(5) NOT NULL,
NOME_MIN_REG VARCHAR(50) NOT NULL,
PIB DECIMAL(12,3) NOT NULL,
POPULACAO INTEGER NOT NULL,
PIB_PEC_CAP DECIMAL(12,3) NOT NULL
);
CREATE TABLE UF
(
COD_UF CHAR(2) NOT NULL PRIMARY KEY,
SIGLA_UF CHAR(2) NOT NULL,
ESTADO VARCHAR(50) NOT NULL
);